version: "3.8"

services:
  db:
    image: postgres:15
    container_name: scinote_db
    volumes:
      - scinote_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: scinote_database
      POSTGRES_PASSWORD: "b621bd4ad3efffb9f289"
      POSTGRES_DB: scinote_database

  web:
    build:
      context: .               # MUST be the root of the cloned SciNote repo
      dockerfile: Dockerfile
    image: scinote_web_production
    container_name: scinote_web
    depends_on:
      - db
    working_dir: /usr/src/app
    env_file:
      - ./production.env
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgresql://scinote_database:b621bd4ad3efffb9f289@db/scinote_database"
    volumes:
      - scinote_files:/usr/src/app/public/system
      - scinote_storage:/usr/src/app/storage

  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    image: scinote_web_production
    container_name: scinote_jobs
    depends_on:
      - db
    working_dir: /usr/src/app
    env_file:
      - ./production.env
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgresql://scinote_database:b621bd4ad3efffb9f289@db/scinote_database"
    command: bundle exec rake jobs:work
    volumes:
      - scinote_files:/usr/src/app/public/system
      - scinote_storage:/usr/src/app/storage

volumes:
  scinote_postgres_data:
  scinote_files:
  scinote_storage:
